### ISSUE TITLE
Contrast does not work correctly on Version 0.9.8 (any version after 0.9.6)

### ISSUE THREAD

**Issue by EugeneMichel** [rsjaffe/MIDI2LR#198]
I wrote about the Contrast issue before in version 0.9.6.1 about a week ago. I then tried the new 0.9.7 version, but after trying it I reverted back to 0.9.6. I am trying 0.9.8 now and I get the same results that I got in 0.9.7. A few people reported a similar issue in other threads but not as thoroughly. I am using BCF2000. 

The issue:

After trying different settings and reopening the app, I am pretty certain this is what happens: (0.9.8)

When I open the app, I can make any adjustments without any problems. The moment I touch the Contrast adjustment thats when the issues begin. Adjusting Contrast will not be responsive and will not be to appropriate slider scale, I can go all the way up and down very fast or very slow and it will slide at the same speed (mostly slowly). _Here is where it gets interesting:_ Any slider or button I use AFTER I adjust Contrast in anyway will continue to adjust CONTRAST, no matter what adjustment is assigned to the slider/button. Thats right!  What happens is Contrast keeps adjusting from 0-100 and then back 100-0 in a continuous loop of death. ANY slider or button I use will take over Contrast (after first time Contrast is adjusted). Buttons will begin to act like a slider and adjust Contrast in a certain amount of "points", up to 100 then back to 0 and back up. I tried most of the assignments, be it Temperature, vignette scale, Paste Selections assignments, - Contrast will keep adjusting back and forth. The only way to fix is to restart the app and everything will work UNTIL Contrast is touched again. I tried making a change and then waiting up to a minute, the buttons still keep adjusting Contrast.

Other users reported inconsistent behavior with Contrast, and I think this is what is happening. What ever was changed AFTER 0.9.6 is the cause. I am using 0.9.6 now for this reason, although I can use 0.9.8 but without a Contrast adjustment assignment (I dont use Contrast much but good to have it assigned). I can make a video if this cant be recreated. When I revert back to 0.9.6 this issue disappears all together. Anyway I can use "merge" send keys to LR feature in 0.9.8 with the Contrast settings of 0.9.6 and have both? Currently I cant use the send keys to LR feature without having broken Contrast. 

Any users experiencing similar issue please leave a note below. Also if you are, then please try version 0.9.6 (not 0.9.6.1) and comment below if you have the same issues still. Thanks!

**Comment by losinternet** [comment]
I had a similar issue with the straighten angle.  No matter what I did once I adjusted the straighten angle, my machine would bog down and then every other control I adjusted on my midi device would adjust the straighten angle.  
But after shutting down lightroom and killing all midi2lr tasks the problem was fixed and has not recurred since. 

Have you tried powering off you midi controller after adjusting contrast?  And then turning it back on?  Maybe an issue in the Juce library? was this updated in 9.7? 

I am using a BCR2000, but have stuck with 9.6.1.

**Comment by alangsr12** [comment]
Me too... the same problem, when I move the Contrast fader, all others controls only move contrast, in a strange way, slowly adjusting back and forth continuously, even pressing some buttons. I use Korg Nanokontrol 2 and in the previously version I dont have problems.

**Comment by rsjaffe** [comment]
The big change in 0.9.7 was an attempt to get around a Lightroom timing bug and a Lightroom Reveal Panels bug by adding the following after Contrast was adjusted:
```lua
        -- LR bug, doesn't reveal panel when Contrast adjusted
        if param=='Contrast' then LrDevelopController.revealPanel(adjustPanel) end
```
Sounds like the Lightroom timing bug is still happening (a control adjustment and panel reveal occurring too close in time to each other causes weird behavior in Lightroom).

Could you try a later version of MIDI2LR (0.9.7 or later), but comment out the line starting "if param ==" by adding two hyphens on the same line before the "if" so it looks like the following? This is in the file "client.lua". If this fixes the problem, then I'll just remove the line, and we'll have to live with Lightroom's reveal panel bug, which is the lesser of the two evils.
```lua
        -- LR bug, doesn't reveal panel when Contrast adjusted
        -- if param=='Contrast' then LrDevelopController.revealPanel(adjustPanel) end
```

**Comment by StevenKersting** [comment]
Commenting out that line resolves the contrast slider issue. 
But I'm getting internal error issues (OSX) with 9.8. And I can't seem to unload 9.8 (at least the app says it's 9.8 regardless of which one I load)
I now get this error on load (regardless of version)
<img width="400" alt="screen shot 2016-02-23 at 4 01 35 pm" src="https://cloud.githubusercontent.com/assets/16807274/13267402/164c87cc-da4b-11e5-86fd-0f37962f40b6.png">

I've also seen this error.
<img width="390" alt="screen shot 2016-02-23 at 4 18 03 pm" src="https://cloud.githubusercontent.com/assets/16807274/13267436/40343bf2-da4b-11e5-966a-7067c37e1bb3.png">

I have tried shutting down/restarting everything.

**Comment by rsjaffe** [comment]
Lightroom cannot unload the plugin. You have to exit Lightroom before changing plugin versions. If you've reloaded while LR is running, you may have a mix of versions loaded, which can cause all sorts of problems.

The second error, in Limits line 185, is really hard to understand. That portion of the program only runs when you've pressed "OK" on the Options dialog, and the values in that table were set when the dialog opened, so those should not be nil. But I'll put guards around that line so that nil values can't leak through.

**Comment by rsjaffe** [comment]
Second beta built and available in releases https://github.com/rsjaffe/MIDI2LR/releases/tag/v0.9.8 should fix most of these issues.
